CREATE TABLE `tblsporttype` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `SportName` varchar(80) DEFAULT NULL,
  `SportNameNumeric` int(4) DEFAULT NULL,
  `Section` varchar(5) DEFAULT NULL,
  `CreationDate` timestamp NULL DEFAULT current_timestamp(),
  `UpdationDate` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;;

INSERT INTO `tblsporttype` (`id`, `SportName`) VALUES
(1,'กรีฑา'),
(2,'ว่ายน้ำ'),
(3,'ฟุตบอล'),
(4,'วอลเลย์บอล'),
(5,'บาสเกตบอล'),
(6,'แบดมินตัน'),
(7,'เซปักตะกร้อ'),
(8,'เทควันโด'),
(9,'ฟุตซอล'),
(10,'เทนนิส'),
(11,'เทเบิลเทนนิส'),
(12,'วอลเลย์บอลชายหาด'),
(13,'เปตอง'),
(14,'เรือพาย'),
(15,'ปันจักสีลัต'),
(16,'รักบี้ฟุตบอล'),
(17,'ยูยิสสู'),
(18,'คาราเต้-โด'),
(19,'กอล์ฟ'),
(20,'ขี่ม้า'),
(21,'เชียร์ลีดดิ้ง'),
(22,'บาสเกตบอล 3 คน'),
(23,'eSport'),
(24,'ลีลาศ'),
(25,'เพาะกายและฟิตเนส'),
(26,'ฮอกกี้'),
(27,'แฮนด์บอล'),
(28,'ปีนหน้าผา'),
(29,'ลอนโบวลส์'),
(30,'ยิงปืน'),
(31,'ดาบสากล'),
(32,'ครอสเวิร์ด'),
(33,'บริดจ์'),
(34,'หมากกระดาน'),
(35,'เอแมท'),
(36,'มวยไทยสมัครเล่น'),
(37,'มวยสากลสมัครเล่น'),
(38,'ยูโด'),
(39,'ยกน้ำหนัก'),
(40,'คำคม'),
(41,'ดาบไทย'),
(42,'แอโรบิก');